services:
  db_service:
    image: postgres:15
    container_name: postgres_db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python_service:
    build: .
    container_name: python_env_container
    ports:
      - "8888:8888"
    volumes:
      - ..:/app
    depends_on:
      - db_service

volumes:
  pgdata: